create table spr_Priviledge
(
    ID   int          not null
        primary key,
    CODE varchar(20)  not null,
    NAME varchar(200) not null
);

INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (1, '1.00000.0001', 'Инвалиды войны');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (2, '1.00000.0009', 'Участники Великой Отечественной войны');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (3, '1.00000.0025', 'Военнослужащие, проходившие военную службу в воинс');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (4, '1.00000.0026', 'Лица, награжденные знаком "Жителю блокадного Ленин');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (5, '1.00000.0027', 'Лица, работавшие в период Великой Отечественной во');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (6, '1.00000.0030', 'Инвалиды I группы');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (7, '1.00000.0031', 'Неработающие инвалиды II группы');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (8, '1.00000.0033', 'Дети-инвалиды');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (9, '1.00000.0036', 'Малочисленные народы Севера, проживающие в сельско');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (10, '1.00000.0037', 'Лица, работавшие на предприятиях, в учреждениях и');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (11, '1.00000.0038', 'Граждане Российской Федерации, удостоенные звания');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (12, '1.00000.0039', 'Бывшие несовершеннолетние узники концлагерей, гетт');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (13, '1.00000.0041', 'Дети первых трех лет жизни');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (14, '1.00000.0042', 'Дети из многодетных семей в возрасте до 6 лет');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (15, '1.00000.0044', 'Граждане, больные гемофилией');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (16, '1.00000.0045', 'Граждане, больные муковисцидозом');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (17, '1.00000.0046', 'Граждане, больные гипофизарным нанизмом');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (18, '1.00000.0047', 'Граждане, больные болезнью Гоше');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (19, '1.00000.0048', 'Граждане, больные злокачественными новообразования');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (20, '1.00000.0049', 'Граждане, больные рассеянным склерозом');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (21, '1.00000.0050', 'Граждане, больные гемолитико-уремическим синдромом');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (22, '1.00000.0051', 'Граждане, больные юношеским артритом с системным н');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (23, '1.00000.0052', 'Граждане, больные мукополисахаридозом I типа');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (24, '1.00000.0053', 'Граждане, больные мукополисахаридозом II типа');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (25, '1.00000.0054', 'Граждане, больные мукополисахаридозом VI типа');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (26, '1.00000.0055', 'Граждане после трансплантации органов и (или) ткан');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (27, '1.00000.0057', 'Отдельные группы населения, страдающие гельминтоза');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (28, '1.00000.0058', 'Граждане, страдающие детскими церебральными парали');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (29, '1.00000.0059', 'Граждане, страдающие гепатоцеребральной дистрофией');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (30, '1.00000.0061', 'Граждане, страдающие острой перемежающейся порфири');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (31, '1.00000.0062', 'Граждане, страдающие СПИД, ВИЧ-инфицированные');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (32, '1.00000.0064', 'Граждане, страдающие гематологическими заболевания');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (33, '1.00000.0066', 'Граждане, страдающие лепрой');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (34, '1.00000.0067', 'Граждане, страдающие туберкулезом');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (35, '1.00000.0068', 'Граждане, страдающие тяжелой формой бруцеллеза');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (36, '1.00000.0069', 'Граждане, страдающие системными хроническими тяжел');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (37, '1.00000.0070', 'Граждане, страдающие бронхиальной астмой');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (38, '1.00000.0071', 'Граждане, страдающие ревматизмом и ревматоидным ар');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (39, '1.00000.0074', 'Граждане, страдающие инфарктом миокарда (первые ше');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (40, '1.00000.0075', 'Граждане с состоянием после операции по протезиров');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (41, '1.00000.0076', 'Граждане, страдающие диабетом');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (42, '1.00000.0078', 'Граждане, страдающие преждевременным половым разви');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (43, '1.00000.0079', 'Граждане, страдающие миастенией');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (44, '1.00000.0080', 'Граждане, страдающие миопатией');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (45, '1.00000.0081', 'Граждане, страдающие мозжечковой атаксией Мари');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (46, '1.00000.0082', 'Граждане, страдающие болезнью Паркинсона');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (47, '1.00000.0083', 'Граждане, страдающие хроническими урологическими з');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (48, '1.00000.0084', 'Граждане, страдающие сифилисом');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (49, '1.00000.0085', 'Граждане, страдающие глаукомой и катарактой');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (50, '1.00000.0087', 'Граждане, страдающие психическими заболеваниями (и');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (51, '1.00000.0088', 'Граждане, страдающие аддисоновой болезнью');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (52, '1.00000.0089', 'Граждане, страдающие шизофренией и эпилепсией');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (53, '1.00000.0092', 'Пенсионеры, получающие пенсию по старости, инвалид');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (54, '1.00000.0093', 'Работающие инвалиды II группы');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (55, '1.00000.0094', 'Инвалиды III группы, признанные в установленном по');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (56, '1.00000.0096', 'Лица, подвергшиеся политическим репрессиям в виде');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (57, '1.00000.0097', 'Военнослужащие, в том числе уволенные в запас (отс');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (58, '1.00000.0098', 'Лица, проработавшие в тылу в период с 22 июня 1941');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (59, '1.00000.0106', 'Граждане, больные апластической анемией неуточненн');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (60, '1.00000.0107', 'Граждане, больные наследственным дефицитом факторо');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (61, '1.00000.0108', 'Граждане, больные пароксизмальной ночной гемоглоби');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (62, '1.00000.0109', 'Граждане, больные идиопатической тромбоцитопеничес');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (63, '1.00000.0110', 'Граждане, имеющие дефект в системе комплемента');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (64, '1.00000.0111', 'Граждане, больные преждевременной половой зрелость');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (65, '1.00000.0112', 'Граждане, страдающие нарушениями обмена ароматичес');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (66, '1.00000.0113', 'Граждане, больные тирозинемии');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (67, '1.00000.0114', 'Граждане, страдающие болезнью "кленового сиропа"');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (68, '1.00000.0115', 'Граждане, страдающие другими видами нарушений обме');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (69, '1.00000.0116', 'Граждане, страдающие нарушениями обмена жирных кис');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (70, '1.00000.0117', 'Граждане, больные гомоцистинурией');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (71, '1.00000.0118', 'Граждане, больные глютарикацидурией');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (72, '1.00000.0119', 'Граждане, больные галактоземией');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (73, '1.00000.0120', 'Граждане, больные другими сфинголипидозами: болезн');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (74, '1.00000.0121', 'Граждане, больные острой перемежающей (печеночной)');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (75, '1.00000.0122', 'Граждане, больные нарушениями обмена меди (болезнь');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (76, '1.00000.0123', 'Граждане, страдающие незавершенным остеогенезом');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (77, '1.00000.0124', 'Граждане, больные легочной (артериальной) гипертен');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (78, '1.00000.0125', 'Граждане, инфицированные вирусом иммунодефицита че');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (79, '1.00000.0126', 'Граждане, больные туберкулезом с множественной лек');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (80, '1.00000.0163', 'Лица, получившие или перенесшие лучевую болезнь ил');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (81, '1.00000.0164', 'Граждане, страдающие онкологическими заболеваниями');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (82, '1.00000.0165', 'Граждане, нуждающиеся в оказании паллиативной меди');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (83, '1.00000.0167', 'Военнослужащие, в том числе уволенные в запас (отс');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (84, '1.00000.0168', 'Военнослужащие, в том числе уволенные в запас (отс');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (85, '1.00000.0169', 'Лица вольнонаемного состава армии и флота, войск и');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (86, '1.00000.0170', 'Сотрудники разведки, контрразведки и другие лица,');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (87, '1.00000.0171', 'Работники предприятий и военных объектов, наркомат');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (88, '1.00000.0172', 'Военнослужащие, в том числе уволенные в запас (отс');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (89, '1.00000.0173', 'Лица, принимавшие участие в боевых действиях проти');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (90, '1.00000.0174', 'Инвалиды Великой Отечественной войны, инвалиды бое');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (91, '1.00000.0175', 'Родители и жены военнослужащих, погибших вследстви');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (92, '1.00000.0178', 'Военнослужащие, в том числе уволенные в запас (отс');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (93, '1.00000.0179', 'Военнослужащие, в том числе уволенные в запас (отс');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (94, '1.00000.0180', 'Военнослужащие автомобильных батальонов, направляв');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (95, '1.00000.0181', 'Военнослужащие летного состава, совершавшие вылеты');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (96, '1.00000.0183', 'Граждане, получившие или перенесшие лучевую болезн');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (97, '1.00000.0184', 'Инвалиды вследствие чернобыльской катастрофы из чи');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (98, '1.00000.0185', 'Граждане (в том числе временно направленных или ко');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (99, '1.00000.0188', 'Граждане (в том числе временно направленные или ко');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (100, '1.00000.0189', 'Рабочие и служащие, а также военнослужащие, лица н');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (101, '1.00000.0190', 'Граждане, эвакуированные (в том числе выехавшие до');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (102, '1.00000.0191', 'Дети и подростки в возрасте до 18 лет, проживающие');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (103, '1.00000.0192', 'Дети и подростки, проживающие на территории зоны п');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (104, '1.00000.0193', 'Дети и подростки, получившие заболевания вследстви');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (105, '1.00000.0194', 'Граждане, постоянно проживающие (работающие) на те');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (106, '1.00000.0195', 'Граждане, постоянно проживающие (работающие) на те');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (107, '1.00000.0196', 'Граждане, постоянно проживающие (работающие) в зон');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (108, '1.00000.0197', 'Лица из числа военнослужащих и вольнонаемного сост');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (109, '1.00000.0204', 'Граждане, страдающие лучевой болезнью');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (110, '1.00000.0205', 'Дети, больные муковисцидозом');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (111, '1.00000.0206', 'Участники Великой Отечественной войны, ставшие инв');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (112, '1.00000.0207', 'Военнослужащие и лица рядового и начальствующего с');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (113, '1.00000.0208', 'Бывшие несовершеннолетние узники концлагерей, гетт');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (114, '1.00000.0209', 'Бывшие несовершеннолетние узники концлагерей, гетт');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (115, '1.00000.0210', 'Члены семей погибших (умерших) инвалидов войны, уч');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (116, '1.00000.0211', 'Члены семей погибших в Великой Отечественной войне');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (117, '1.00000.0212', 'Члены семей военнослужащих, лиц рядового и начальс');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (118, '1.00000.0213', 'Члены семей военнослужащих, погибших в плену, приз');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (119, '1.00000.0214', 'Родители и жены погибших военнослужащих при защите');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (120, '1.00000.0215', 'Ветераны боевых действий:
1) военнослужащие, в том');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (121, '1.00000.0216', 'Инвалиды III группы');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (122, '1.00000.0217', 'Инвалиды II группы');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (123, '1.00000.0218', 'Инвалиды I группы');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (124, '1.00000.0219', 'Граждане, получившие или перенесшие лучевую болезн');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (125, '1.00000.0220', 'Инвалиды вследствие чернобыльской катастрофы');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (126, '1.00000.0221', 'Граждане (в том числе временно направленные или ко');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (127, '1.00000.0222', 'Граждане (в том числе временно направленные или ко');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (128, '1.00000.0223', 'Граждане, эвакуированные (в том числе выехавшие до');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (129, '1.00000.0224', 'Граждане, постоянно проживающие (работающие) на те');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (130, '1.00000.0225', 'Граждане, постоянно проживающие (работающие) на те');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (131, '1.00000.0226', 'Граждане, постоянно проживающие (работающие) в зон');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (132, '1.00000.0227', 'Дети и подростки в возрасте до 18 лет, проживающие');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (133, '1.00000.0228', 'Дети и подростки, страдающие болезнями вследствие');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (134, '1.00000.0229', 'Дети и подростки, страдающие болезнями вследствие');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (135, '1.00000.0230', 'Дети и подростки в возрасте до 18 лет, постоянно п');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (136, '1.00000.0231', 'Рабочие и служащие, а также военно-служащие,  лица');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (137, '1.00000.0232', 'Рабочие и служащие, а также военно-служащих, лица');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (138, '1.00000.0233', 'Граждане, ставшие инвалидами в результате воздейст');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (139, '1.00000.0234', 'Граждане, получившие лучевую болезнь, другие забол');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (140, '1.00000.0235', 'Граждане (в том числе временно напра-вленные или к');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (141, '1.00000.0236', 'Граждане (в том числе временно направленные или ко');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (142, '1.00000.0237', 'Граждане, эвакуированные (переселенные), а также д');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (143, '1.00000.0238', 'Граждане, проживающие в населенных пунктах, подвер');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (144, '1.00000.0239', 'Дети, не достигшие возраста 18 лет, проживающие в');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (145, '1.00000.0240', 'Дети первого и второго поколения граждан, указанны');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (146, '1.00000.0241', 'Граждане из подразделений особого риска, имеющие и');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (147, '1.00000.0242', 'Граждане из подразделений особого риска, не имеющи');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (148, '1.00000.0243', 'Граждане, получившие суммарную (накопительную) эфф');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (149, '1.00000.0244', 'Граждане, получившие суммарную (накопительную) эфф');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (150, '1.00000.0245', 'Дети в возрасте до 18 лет первого и второго поколе');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (151, '1.00000.0246', 'Лица, которые перенесли острое нарушение мозгового');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (152, '1.00000.0247', 'Лица, работавшие в годы Великой Отечественной войн');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (153, '1.00000.0248', 'Дети-инвалиды в возрасте до 18 лет');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (154, '1.00000.0249', 'Граждане, больные гипофизарным нанизмом');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (155, '1.00000.0250', 'Граждане, больные рассеянным склерозом');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (156, '1.00000.0251', 'Граждане после пересадки органов и тканей');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (157, '1.00000.0252', 'Лица, которые перенесли острое нарушение мозгового');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (158, '1.00000.0253', 'Лица, награжденные знаком «Жителю осажденного Сева');
INSERT INTO ambulatoryCases.spr_Priviledge (ID, CODE, NAME) VALUES (159, '0', 'Нет льгот');
