create table spr_SMO
(
    ID   int          not null
        primary key,
    NAME varchar(500) not null
);

INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (1, 'АДЫГЕЙСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (2, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В ГОРОДЕ УФЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (3, 'ФИЛИАЛ ООО СМК "АСТРА-МЕТАЛЛ" В РЕСПУБЛИКЕ БАШКОРТОСТАН');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (4, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В РЕСПУБЛИКЕ БАШКОРТОСТАН');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (5, 'УФИМСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (6, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВОЕ МЕДИЦИНСКОЕ ОБЩЕСТВО "СПАСЕНИЕ" В РЕСПУБЛИКЕ БАШКОРТОСТАН "БАШКИРСКАЯ МЕДИЦИНСКАЯ СТРАХОВАЯ КОМПАНИЯ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (7, 'ФИЛИАЛ "БАШКОРТОСТАН" ООО "АЛЬФАСТРАХОВАНИЕ-ОМС"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (8, 'УФИМСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ РЕСО-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (9, 'БУРЯТСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (10, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В РЕСПУБЛИКЕ БУРЯТИЯ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (11, 'ФИЛИАЛ ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В РЕСПУБЛИКЕ АЛТАЙ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (12, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В ГОРОДЕ МАХАЧКАЛЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (13, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В Г. НАЗРАНИ.');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (14, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В КАБАРДИНО-БАЛКАРСКОЙ РЕСПУБЛИКЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (15, 'КАБАРДИНО-БАЛКАРСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ РЕСО-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (16, 'КАЛМЫЦКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (17, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В ГОРОДЕ ЧЕРКЕССКЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (18, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М" В Г.ПЕТРОЗАВОДСК');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (19, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ РЕСО-МЕД" КАРЕЛЬСКИЙ ФИЛИАЛ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (20, 'СЫКТЫВКАРСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (21, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В РЕСПУБЛИКЕ КОМИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (22, 'МАРИЙСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (23, 'МОРДОВСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (24, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В РЕСПУБЛИКЕ МОРДОВИЯ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (25, 'АКЦИОНЕРНОЕ ОБЩЕСТВО "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ "САХАМЕДСТРАХ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (26, 'ФИЛИАЛ ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В РЕСПУБЛИКЕ САХА (ЯКУТИЯ)');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (27, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В РЕСПУБЛИКЕ СЕВЕРНАЯ ОСЕТИЯ-АЛАНИЯ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (28, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "АК БАРС-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (29, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВОЕ МЕДИЦИНСКОЕ ОБЩЕСТВО "СПАСЕНИЕ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (30, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ СТРАХОВАЯ МЕДИЦИНСКАЯ ОРГАНИЗАЦИЯ "ЧУЛПАН-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (31, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В РЕСПУБЛИКЕ ТЫВА');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (32, 'ИЖЕВСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ВСК-МИЛОСЕРДИЕ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (33, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М" В Г.ИЖЕВСКЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (34, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В УДМУРТСКОЙ РЕСПУБЛИКЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (35, 'УДМУРТСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (36, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (37, 'ХАКАССКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ "РЕСО-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (38, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В ГОРОДЕ ГРОЗНЫЙ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (39, 'АКЦИОНЕРНОЕ ОБЩЕСТВО "ЧУВАШСКАЯ МЕДИЦИНСКАЯ СТРАХОВАЯ КОМПАНИЯ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (40, 'АКЦИОНЕРНОЕ ОБЩЕСТВО "СТРАХОВАЯ КОМПАНИЯ "ЧУВАШИЯ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (41, 'АЛТАЙСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ РЕСО-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (42, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В АЛТАЙСКОМ КРАЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (43, 'КРАСНОДАРСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "АЛЬФАСТРАХОВАНИЕ-ОМС"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (44, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В КРАСНОДАРСКОМ КРАЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (45, 'КРАСНОДАРСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (46, 'КРАСНОЯРСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ СТРАХОВАЯ КОМПАНИЯ "КАПИТАЛ-ПОЛИС МЕДИЦИНА"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (47, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М" В Г.КРАСНОЯРСК - МЕДИКА-ВОСТОК');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (48, 'КРАСНОЯРСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (49, 'КРАСНОЯРСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ РЕСО-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (50, 'АКЦИОНЕРНОЕ ОБЩЕСТВО "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (51, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ СТРАХОВАЯ МЕДИЦИНСКАЯ ОРГАНИЗАЦИЯ "ВОСТОЧНО-СТРАХОВОЙ АЛЬЯНС"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (52, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М" В Г. СТАВРОПОЛЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (53, 'СТАВРОПОЛЬСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (54, 'ХАБАРОВСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (55, 'АМУРСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (56, 'АРХАНГЕЛЬСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (57, 'ФИЛИАЛ ООО «КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ» В АРХАНГЕЛЬСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (58, 'АСТРАХАНСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (59, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ " В ГОРОДЕ БЕЛГОРОДЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (60, 'БЕЛГОРОДСКИЙ ФИЛИАЛ ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МЕДИЦИНСКАЯ СТРАХОВАЯ КОМПАНИЯ "ИНКО-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (61, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М" В Г. БРЯНСК');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (62, 'БРЯНСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (63, 'БРЯНСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "АЛЬФАСТРАХОВАНИЕ-ОМС"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (64, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В ГОРОДЕ ВЛАДИМИРЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (65, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М" В Г.ВЛАДИМИР');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (66, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" ВО ВЛАДИМИРСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (67, 'ВОЛГОГРАДСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ - МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (68, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В ВОЛГОГРАДСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (69, 'ВОЛОГОДСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (70, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МЕДИЦИНСКАЯ СТРАХОВАЯ КОМПАНИЯ "ИНКО-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (71, 'ВОРОНЕЖСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (72, 'ИВАНОВСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (73, 'АКЦИОНЕРНОЕ ОБЩЕСТВО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (74, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (75, 'КАЛИНИНГРАДСКИЙ ФИЛИАЛ АКЦИОНЕРНОЕ ОБЩЕСТВО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (76, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В КАЛИНИНГРАДСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (77, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В ГОРОДЕ КАЛУГЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (78, 'КАЛУЖСКИЙ ФИЛИАЛ АО"СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (79, 'КАМЧАТСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (80, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М" В Г.КЕМЕРОВО');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (81, 'КУЗБАССКИЙ ФИЛИАЛ ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "АЛЬФАСТРАХОВАНИЕ-ОМС"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (82, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В ГОРОДЕ КИРОВЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (83, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М" В Г. КИРОВ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (84, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В КИРОВСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (85, 'КИРОВСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (86, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В КОСТРОМСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (87, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В ГОРОДЕ КОСТРОМЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (88, 'КОСТРОМСКОЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (89, 'ФИЛИАЛ СТРАХОВОЙ МЕДИЦИНСКОЙ КОМПАНИИ "АСТРАМЕД-МС" (АКЦИОНЕРНОЕ ОБЩЕСТВО) В Г.КУРГАН');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (90, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В КУРГАНСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (91, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М" В Г. КУРСКЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (92, 'КУРСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МЕДИЦИНСКАЯ СТРАХОВАЯ КОМПАНИЯ "ИНКО-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (93, 'КУРСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (94, 'АКЦИОНЕРНОЕ ОБЩЕСТВО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД" ( САНКТ-ПЕТЕРБУРГСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД")');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (95, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" (ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В Г. САНКТ-ПЕТЕРБУРГЕ И ЛЕНИНГРАДСКОЙ ОБЛАСТИ)');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (96, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ РЕСО-МЕД" ( СЕВЕРО-ЗАПАДНЫЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ РЕСО-МЕД")');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (97, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В ЛИПЕЦКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (98, 'ЛИПЕЦКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (99, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ "САХАМЕДСТРАХ" В ГОРОДЕ МАГАДАНЕ МАГАДАНСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (100, 'МАГАДАНСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (101, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ РЕСО-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (102, 'АКЦИОНЕРНОЕ ОБЩЕСТВО "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (103, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МЕДИЦИНСКАЯ СТРАХОВАЯ КОМПАНИЯ "МЕДСТРАХ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (104, 'АКЦИОНЕРНОЕ ОБЩЕСТВО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (105, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (106, 'МУРМАНСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (107, 'МУРМАНСКИЙ ФИЛИАЛ ООО "АЛЬФАСТРАХОВАНИЕ-ОМС"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (108, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М" В Г. НИЖНИЙ НОВГОРОД');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (109, 'НИЖЕГОРОДСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ РЕСО-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (110, 'НИЖЕГОРОДСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (111, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В НИЖЕГОРОДСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (112, 'НОВГОРОДСКИЙ ФИЛИАЛ ООО "АЛЬФАСТРАХОВАНИЕ - ОМС"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (113, 'НОВГОРОДСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (114, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ ОРГАНИЗАЦИЯ "СИМАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (115, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М" В Г. НОВОСИБИРСК');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (116, 'НОВОСИБИРСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (117, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В ОМСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (118, 'ОМСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (119, 'ОМСКИЙ ФИЛИАЛ ООО "АЛЬФАСТРАХОВАНИЕ-ОМС"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (120, 'ОРЕНБУРГСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (121, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М" В Г. ОРЕНБУРГ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (122, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В ГОРОДЕ ОРЕНБУРГЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (123, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В ОРЕНБУРГСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (124, 'ОРЛОВСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (125, 'ОРЛОВСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ РЕСО-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (126, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В ГОРОДЕ ПЕНЗЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (127, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В ПЕНЗЕНСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (128, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В Г.ПЕРМИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (129, 'ФИЛИАЛ СТРАХОВОЙ МЕДИЦИНСКОЙ КОМПАНИИ "АСТРАМЕД-МС" (АО) В Г.ПЕРМЬ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (130, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (131, 'ПЕРМСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ "РЕСО-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (132, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В ГОРОДЕ ПСКОВЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (133, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ МЕДИЦИНСКОЕ СТРАХОВОЕ ОБЩЕСТВО "ПАНАЦЕЯ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (134, 'РОСТОВСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (135, 'РОСТОВСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (136, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В РОСТОВСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (137, 'РОСТОВСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "АЛЬФАСТРАХОВАНИЕ-ОМС"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (138, 'РЯЗАНСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (139, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В РЯЗАНСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (140, 'АКЦИОНЕРНОЕ ОБЩЕСТВО "СТРАХОВАЯ КОМПАНИЯ "АСКОМЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (141, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В ГОРОДЕ САМАРЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (142, 'САРАТОВСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (143, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В ГОРОДЕ САРАТОВЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (144, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В САРАТОВСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (145, 'САХАЛИНСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (146, 'СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ "АСТРАМЕД-МС" (АКЦИОНЕРНОЕ ОБЩЕСТВО)');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (147, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ CТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ "УРАЛ-РЕЦЕПТ М"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (148, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ "УГМК-МЕДИЦИНА"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (149, 'ЕКАТЕРИНБУРГСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (150, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М" В Г. ЕКАТЕРИНБУРГЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (151, 'СМОЛЕНСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (152, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В Г.СМОЛЕНСКЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (153, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В СМОЛЕНСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (154, 'ТАМБОВСКИЙ ФИЛИАЛ АКЦИОНЕРНОЕ ОБЩЕСТВО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (155, 'ТВЕРСКОЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ РЕСО-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (156, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В Г. ТВЕРИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (157, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В ТВЕРСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (158, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (159, 'ТВЕРСКОЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "АЛЬФАСТРАХОВАНИЕ-ОМС"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (160, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В ГОРОДЕ ТОМСКЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (161, 'ТОМСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (162, 'ТУЛЬСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "АЛЬФАСТРАХОВАНИЕ-ОМС"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (163, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В ТУЛЬСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (164, 'ТЮМЕНСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (165, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" (ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В ТЮМЕНСКОЙ ОБЛАСТИ)');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (166, 'ТЮМЕНСКИЙ ФИЛИАЛ ООО "АЛЬФАСТРАХОВАНИЕ - ОМС"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (167, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В УЛЬЯНОВСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (168, 'УЛЬЯНОВСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (169, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ "АСТРА-МЕТАЛЛ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (170, 'ЧЕЛЯБИНСКИЙ ФИЛИАЛ ООО "СМК РЕСО-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (171, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М", ФИЛИАЛ В Г. ЧЕЛЯБИНСК');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (172, 'ЕКАТЕРИНБУРГСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (173, 'ЧЕЛЯБИНСКИЙ ФИЛИАЛ ООО "АЛЬФАСТРАХОВАНИЕ-ОМС"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (174, 'ГОСУДАРСТВЕННОЕ УНИТАРНОЕ ПРЕДПРИЯТИЕ ЗАБАЙКАЛЬСКОГО КРАЯ "ГОСУДАРСТВЕННАЯ СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ "ЗАБАЙКАЛМЕДСТРАХ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (175, 'ЯРОСЛАВCКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ РЕСО-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (176, 'ЯРОСЛАВСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (177, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В ЯРОСЛАВСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (178, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М" В Г. ЯРОСЛАВЛЬ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (179, 'АКЦИОНЕРНОЕ ОБЩЕСТВО "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (180, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "МЕДИЦИНСКАЯ СТРАХОВАЯ КОМПАНИЯ "МЕДСТРАХ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (181, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ РЕСО-МЕД" (МОСКОВСКИЙ ФИЛИАЛ)');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (182, 'АКЦИОНЕРНОЕ ОБЩЕСТВО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (183, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ КОМПАНИЯ "ИНГОССТРАХ-М"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (184, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" (ФИЛИАЛ ООО "КАПИТАЛ МС" В Г. МОСКВЕ)');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (185, 'АКЦИОНЕРНОЕ ОБЩЕСТВО "ГОРОДСКАЯ СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (186, 'САНКТ-ПЕТЕРБУРГСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ СТРАХОВАЯ КОМПАНИЯ "КАПИТАЛ-ПОЛИС МЕДИЦИНА"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (187, 'ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "МЕДИЦИНСКАЯ АКЦИОНЕРНАЯ СТРАХОВАЯ КОМПАНИЯ" В ГОРОДЕ САНКТ-ПЕТЕРБУРГЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (188, 'САНКТ-ПЕТЕРБУРГСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ РЕСО-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (189, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В Г. САНКТ-ПЕТЕРБУРГЕ И ЛЕНИНГРАДСКОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (190, 'САНКТ-ПЕТЕРБУРГСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (191, 'ФИЛИАЛ ООО "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В ЕВРЕЙСКОЙ АВТОНОМНОЙ ОБЛАСТИ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (192, 'ДИРЕКЦИЯ ЕВРЕЙСКОЙ АВТОНОМНОЙ ОБЛАСТИ ХАБАРОВСКОГО ФИЛИАЛА АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (193, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В НЕНЕЦКОМ АВТОНОМНОМ ОКРУГЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (194, 'ЮГОРСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (195, 'ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "КАПИТАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ" В ХАНТЫ-МАНСИЙСКОМ АВТОНОМНОМ ОКРУГЕ - ЮГРЕ');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (196, 'ХАНТЫ-МАНСИЙСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "АЛЬФАСТРАХОВАНИЕ-ОМС"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (197, 'ЧУКОТСКИЙ ФИЛИАЛ АКЦИОНЕРНОГО ОБЩЕСТВА "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (198, 'АКЦИОНЕРНОЕ ОБЩЕСТВО "ГОСУДАРСТВЕННАЯ МЕДИЦИНСКАЯ СТРАХОВАЯ КОМПАНИЯ "ЗАПОЛЯРЬЕ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (199, 'АКЦИОНЕРНОЕ ОБЩЕСТВО "МЕДИЦИНСКАЯ СТРАХОВАЯ КОМПАНИЯ "НОВЫЙ УРЕНГОЙ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (200, 'ЯМАЛЬСКИЙ ФИЛИАЛ АО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (201, 'БАЙКОНУРСКИЙ ФИЛИАЛ АКЦИОНЕРНОЕ ОБЩЕСТВО "СТРАХОВАЯ КОМПАНИЯ "СОГАЗ-МЕД"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (202, 'ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "CТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ "КРЫММЕДСТРАХ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (203, 'ФИЛИАЛ "КРЫМСКАЯ СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ" ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "АРСЕНАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (204, 'СЕВАСТОПОЛЬСКИЙ ФИЛИАЛ "КРЫМСКОЙ СТРАХОВОЙ МЕДИЦИНСКОЙ КОМПАНИИ" ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "АРСЕНАЛ МЕДИЦИНСКОЕ СТРАХОВАНИЕ"');
INSERT INTO ambulatoryCases.spr_SMO (ID, NAME) VALUES (205, 'СЕВАСТОПОЛЬСКИЙ ФИЛИАЛ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "СТРАХОВАЯ МЕДИЦИНСКАЯ КОМПАНИЯ "КРЫММЕДСТРАХ"');
