create table spr_Speciality
(
    ID   int          not null
        primary key,
    NAME varchar(100) not null
);

INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (1, 'Лечебное дело');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (2, 'Медико-профилактическое дело');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (3, 'Стоматология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (4, 'Фармация');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (5, 'Сестринское дело');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (6, 'Медицинская биохимия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (7, 'Медицинская биофизика');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (8, 'Акушерство и гинекология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (9, 'Анестезиология - реаниматология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (10, 'Дерматовенерология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (11, 'Детская хирургия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (12, 'Генетика');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (13, 'Клиническая лабораторная диагностика');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (14, 'Неврология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (15, 'Неонатология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (16, 'Общая врачебная практика (семейная медицина)');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (17, 'Онкология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (18, 'Организация здравоохранения и общественное здоровье');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (19, 'Оториноларингология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (20, 'Офтальмология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (21, 'Патологическая анатомия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (22, 'Педиатрия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (23, 'Психиатрия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (24, 'Рентгенология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (25, 'Скорая медицинская помощь');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (26, 'Судебно-медицинская экспертиза');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (27, 'Терапия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (28, 'Травматология и ортопедия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (29, 'Фтизиатрия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (30, 'Хирургия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (31, 'Эндокринология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (32, 'Инфекционные болезни');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (33, 'Ультразвуковая диагностика');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (34, 'Физиотерапия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (35, 'Функциональная диагностика');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (36, 'Эндоскопия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (37, 'Токсикология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (38, 'Трансфузиология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (40, 'Клиническая микология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (41, 'Детская онкология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (42, 'Детская урология - андрология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (43, 'Колопроктология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (44, 'Нейрохирургия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (45, 'Сердечно-сосудистая хирургия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (46, 'Торакальная хирургия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (50, 'Челюстно-лицевая хирургия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (52, 'Лабораторная генетика');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (54, 'Бактериология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (55, 'Вирусология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (57, 'Лабораторная микология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (58, 'Восстановительная медицина');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (59, 'Лечебная физкультура и спортивная медицина');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (61, 'Мануальная терапия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (62, 'Рефлексотерапия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (66, 'Гериатрия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (75, 'Сурдология - оториноларингология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (77, 'Аллергология и иммунология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (79, 'Гастроэнтерология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (80, 'Гематология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (81, 'Детская кардиология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (83, 'Детская эндокринология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (84, 'Диетология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (85, 'Клиническая фармакология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (89, 'Нефрология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (90, 'Пульмонология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (91, 'Ревматология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (97, 'Психиатрия-наркология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (98, 'Психотерапия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (99, 'Сексология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (100, 'Судебно-психиатрическая экспертиза');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (102, 'Радиология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (110, 'Авиационная и космическая медицина');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (118, 'Кардиология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (124, 'Профпатология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (145, 'Урология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (150, 'Диабетология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (152, 'Общая гигиена');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (153, 'Социальная гигиена и организация госсанэпидслужбы');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (154, 'Эпидемиология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (159, 'Гигиена детей и подростков');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (160, 'Гигиена питания');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (161, 'Гигиена труда');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (162, 'Гигиеническое воспитание');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (163, 'Коммунальная гигиена');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (164, 'Радиационная гигиена');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (165, 'Санитарно-гигиенические лабораторные исследования');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (169, 'Дезинфектология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (170, 'Паразитология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (171, 'Стоматология общей практики');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (173, 'Ортодонтия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (174, 'Стоматология детская');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (175, 'Стоматология ортопедическая');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (176, 'Стоматология терапевтическая');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (177, 'Стоматология хирургическая');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (184, 'Управление и экономика фармации');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (185, 'Фармацевтическая химия и фармакогнозия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (186, 'Управление сестринской деятельностью');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (204, 'Средний медицинский персонал');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (205, 'Организация сестринского дела');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (206, 'Лечебное дело');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (207, 'Акушерское дело');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (208, 'Стоматология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (209, 'Стоматология ортопедическая');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (210, 'Эпидемиология (паразитология)');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (211, 'Гигиена и санитария');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (212, 'Дезинфекционное дело');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (213, 'Гигиеническое воспитание');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (214, 'Энтомология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (215, 'Лабораторная диагностика');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (216, 'Гистология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (217, 'Лабораторное дело');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (218, 'Фармация');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (219, 'Сестринское дело');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (221, 'Сестринское дело в педиатрии');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (222, 'Операционное дело');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (223, 'Анестезиология и реаниматология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (224, 'Общая практика');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (225, 'Рентгенология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (226, 'Функциональная диагностика');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (227, 'Физиотерапия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (228, 'Медицинский массаж');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (229, 'Фармацевтическая технология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (230, 'Лечебная физкультура');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (231, 'Диетология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (232, 'Медицинская статистика');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (233, 'Стоматология профилактическая');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (234, 'Судебно-медицинская экспертиза');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (235, 'Медицинская оптика');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (236, 'Медико-социальная экспертиза');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (247, 'Пластическая хирургия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (248, 'Рентгенэндоваскулярные диагностика и лечение');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (252, 'Косметология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (256, 'Водолазная медицина');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (269, 'Медицинская кибернетика');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (279, 'Медико-социальная помощь');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (280, 'Наркология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (281, 'Реабилитационное сестринское дело');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (282, 'Сестринское дело в косметологии');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (283, 'Скорая и неотложная помощь');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (284, 'Бактериология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (285, 'Радиотерапия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (287, 'Остеопатия');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (288, 'Детская онкология-гематология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (289, 'Медицинская микробиология');
INSERT INTO ambulatoryCases.spr_Speciality (ID, NAME) VALUES (290, 'Физическая и реабилитационная медицина');
